const GAME_DATA = {
  salary: 200,
  startingCash: 1500,
  maxUpgrades: 5,
  groups: {
    brown: { name: "Faction Border", color: "#9b6b4a" },
    cyan: { name: "Lowsec Front", color: "#53cbd8" },
    magenta: { name: "Northern Approach", color: "#c45ab3" },
    orange: { name: "Old Rental Belt", color: "#e99b42" },
    red: { name: "Southern Front", color: "#e05255" },
    yellow: { name: "Dronelands", color: "#e6c54f" },
    green: { name: "Bloc Heartland", color: "#4eb07c" },
    blue: { name: "Landlord's Row", color: "#437ed8" }
  },
  spaces: [
    { type: "corner", name: "Undock", icon: "◆", text: "Collect 200M when your clone completes the circuit." },
    { type: "property", name: "The Bleak Lands", group: "brown", price: 60, buildCost: 50, rent: [2, 10, 30, 90, 160, 250], flavor: "Amarr and Minmatar pilots argue over who owns the button." },
    { type: "card", deck: "mail", name: "Alliance Mail", icon: "✉", text: "This ping could have been a forum post." },
    { type: "property", name: "Black Rise", group: "brown", price: 60, buildCost: 50, rent: [4, 20, 60, 180, 320, 450], flavor: "Every gate is clear according to the scout who died there." },
    { type: "tax", name: "Sov Bill", amount: 200, icon: "▤", text: "Infrastructure was the cheap part." },
    { type: "transit", name: "Hek → Turnur", price: 200, icon: "⇄", text: "Definitely shorter. Do not check fuel costs." },
    { type: "property", name: "Placid", group: "cyan", price: 100, buildCost: 50, rent: [6, 30, 90, 270, 400, 550], flavor: "The Gallente militia has captured this system again. Probably." },
    { type: "card", deck: "local", name: "Local Spike", icon: "⌁", text: "One neutral. Thirty docked Ishtars." },
    { type: "property", name: "Providence", group: "cyan", price: 100, buildCost: 50, rent: [6, 30, 90, 270, 400, 550], flavor: "NRDS lasted longer than most rental contracts." },
    { type: "property", name: "Catch", group: "cyan", price: 120, buildCost: 50, rent: [8, 40, 100, 300, 450, 600], flavor: "The traditional highway for fleets going somewhere more expensive." },
    { type: "corner", name: "Winning EVE", caption: "TOUCH GRASS", icon: "⚠", text: "You finally went outside. You're still checking r/Eve. Jail rules apply; landing here normally is just visiting." },
    { type: "property", name: "Pure Blind", group: "magenta", price: 140, buildCost: 100, rent: [10, 50, 150, 450, 625, 750], flavor: "Small-gang content with coalition-sized consequences." },
    { type: "utility", name: "Skyhook Office", price: 150, icon: "⌬", text: "Planetary theft, now with paperwork." },
    { type: "property", name: "Fade", group: "magenta", price: 140, buildCost: 100, rent: [10, 50, 150, 450, 625, 750], flavor: "A quiet northern region until somebody looks at the map." },
    { type: "property", name: "Deklein", group: "magenta", price: 160, buildCost: 100, rent: [12, 60, 180, 500, 700, 900], flavor: "History says your security deposit is gone." },
    { type: "transit", name: "1DQ → T5ZI", price: 200, icon: "⇄", text: "The longest short trip in New Eden." },
    { type: "property", name: "Geminate", group: "orange", price: 180, buildCost: 100, rent: [14, 70, 200, 550, 750, 950], flavor: "A floodplain with excellent ratting and a flexible definition of safe." },
    { type: "card", deck: "mail", name: "Alliance Mail", icon: "✉", text: "Subject: final_final_doctrine_v7." },
    { type: "property", name: "Tribute", group: "orange", price: 180, buildCost: 100, rent: [14, 70, 200, 550, 750, 950], flavor: "The name was a rental joke before this board existed." },
    { type: "property", name: "Vale of the Silent", group: "orange", price: 200, buildCost: 100, rent: [16, 80, 220, 600, 800, 1000], flavor: "Silent except for intel pings, Ishtar drones, and eviction notices." },
    { type: "corner", name: "Freeport Keepstar", icon: "◇", text: "Docking rights may change while you read this sentence." },
    { type: "property", name: "Cache", group: "red", price: 220, buildCost: 150, rent: [18, 90, 250, 700, 875, 1050], flavor: "Far enough away that every move-op becomes a personality test." },
    { type: "card", deck: "local", name: "Local Spike", icon: "⌁", text: "Intel says five. D-scan says sixty." },
    { type: "property", name: "Insmother", group: "red", price: 220, buildCost: 150, rent: [18, 90, 250, 700, 875, 1050], flavor: "Your landlord calls it strategic depth. You call it twelve cynos from Jita." },
    { type: "property", name: "Wicked Creek", group: "red", price: 240, buildCost: 150, rent: [20, 100, 300, 750, 925, 1100], flavor: "Good truesec. Better excuses for not forming." },
    { type: "transit", name: "MJ-5F9 → BWF-ZZ", price: 200, icon: "⇄", text: "Ansiblex offline. Please contact someone with roles." },
    { type: "property", name: "Perrigen Falls", group: "yellow", price: 260, buildCost: 150, rent: [22, 110, 330, 800, 975, 1150], flavor: "The drone hordes do not drop loot. The invoice still does." },
    { type: "property", name: "Oasa", group: "yellow", price: 260, buildCost: 150, rent: [22, 110, 330, 800, 975, 1150], flavor: "Prime rental acreage if you enjoy jump-freighter spreadsheets." },
    { type: "utility", name: "ESS Reserve Bank", price: 150, icon: "◈", text: "The keys are safe. The grid is not." },
    { type: "property", name: "Malpais", group: "yellow", price: 280, buildCost: 150, rent: [24, 120, 360, 850, 1025, 1200], flavor: "Farms, fields, and a standing fleet ten jumps away." },
    { type: "gotojail", name: "Banned for RMT", icon: "»", text: "CCP helped you win EVE. Go directly to Winning EVE and touch grass. Do not pass Undock. Do not collect 200M." },
    { type: "property", name: "Fountain", group: "green", price: 300, buildCost: 200, rent: [26, 130, 390, 900, 1100, 1275], flavor: "Beautiful NPCs, scenic pipes, and neighbors who own supercapitals." },
    { type: "property", name: "Querious", group: "green", price: 300, buildCost: 200, rent: [26, 130, 390, 900, 1100, 1275], flavor: "Buffer space is still space. Rent is still rent." },
    { type: "card", deck: "mail", name: "Alliance Mail", icon: "✉", text: "Mandatory fun begins at 01:00." },
    { type: "property", name: "Delve", group: "green", price: 320, buildCost: 200, rent: [28, 150, 450, 1000, 1200, 1400], flavor: "Real estate value measured in Keepstars and grudges." },
    { type: "transit", name: "BKG → 4-HWWF", price: 200, icon: "⇄", text: "Twenty light-years saved. One blue standings incident created." },
    { type: "card", deck: "local", name: "Local Spike", icon: "⌁", text: "They brought combat probes. You brought optimism." },
    { type: "property", name: "Branch", group: "blue", price: 350, buildCost: 200, rent: [35, 175, 500, 1100, 1300, 1500], flavor: "Northern income property with seasonal invasion views." },
    { type: "tax", name: "War Bond", amount: 100, icon: "₭", text: "Temporary coalition tax. Since 2016." },
    { type: "property", name: "Tenal", group: "blue", price: 400, buildCost: 200, rent: [50, 200, 600, 1400, 1700, 2000], flavor: "End-of-the-map luxury for the discerning AFK ratter." }
  ],
  mailCards: [
    { title: "Move-op cancelled", body: "Unpack the freighter. FC changed staging while you were loading it. Advance to Undock and collect 200M.", source: "research.html#card-renters", effect: { type: "move", index: 0 } },
    { title: "Jita doubler paid out", body: "Collect 200M. You are the screenshot they show the next guy.", source: "research.html#card-doubler", effect: { type: "cash", value: 200 } },
    { title: "SRP denied", body: "You brought a civilian afterburner to a doctrine fleet. The SRP officer pinned your lossmail. Pay 50M.", source: "research.html#card-fleet", effect: { type: "cash", value: -50 } },
    { title: "Didn't want that ship anyway", body: "The salvage sold for more than the fit. Collect 50M.", source: "research.html#card-coping", effect: { type: "cash", value: 50 } },
    { title: "Streamer Privilege", kicker: "THE LORU DISCOURSE SPECIAL", body: "Your ban expires before the megathread does. You didn't even finish touching grass. Get out of Winning EVE free. Keep this card until needed, or trade it.", source: "research.html#streamer", effect: { type: "escape" } },
    { title: "The wallet has receipts", body: "Your rental ledger includes a PayPal column. Go directly to Winning EVE. Your new standing fleet is the dog. Do not pass Undock or collect 200M.", source: "research.html#card-security", effect: { type: "jail" } },
    { title: "Already replaced", body: "Your ship died before the SRP form loaded. Finance paid anyway. Collect 100M.", source: "research.html#card-fleet", effect: { type: "cash", value: 100 } },
    { title: "B-R accounting department", body: "You paid the sov bill twice. After B-R, nobody complained. Accounting refunds 20M.", source: "research.html#card-br", effect: { type: "cash", value: 20 } },
    { title: "Birthday welp fleet", body: "Everyone brought fireworks and forgot the logi. Collect 10M from every other pilot for the replacement hull.", source: "research.html#card-birthday", effect: { type: "collectAll", value: 10 } },
    { title: "Platinum insurance", body: "The payout arrived before the FC finished explaining why that was a good feed. Collect 100M.", source: "research.html#card-insurance", effect: { type: "cash", value: 100 } },
    { title: "Asakai reenactment", body: "You jumped the titan instead of bridging the fleet. The rescue fleet also needs rescuing. Pay 100M.", source: "research.html#card-asakai", effect: { type: "cash", value: -100 } },
    { title: "Spreadsheets in space", body: "The landlord promoted you to Accounts Receivable. Pay 50M for Excel training.", source: "research.html#card-excel", effect: { type: "cash", value: -50 } },
    { title: "OreBnB cleaning fee", body: "The departing tenant left drones in every anomaly. Collect 25M.", source: "research.html#card-renters", effect: { type: "cash", value: 25 } },
    { title: "Forsaken Fortress", body: "Your landlord ignored the fuel mails. Now the neighbors are bringing haulers to the bash. Pay 40M per Astrahus and 115M per Keepstar you own for repairs.", source: "research.html#card-fuel", effect: { type: "classicRepairs", house: 40, hotel: 115 } },
    { title: "Monocle contest runner-up", body: "Collect 10M for second place. The winner is busy shooting the Jita monument.", source: "research.html#card-monocle", effect: { type: "cash", value: 10 } },
    { title: "Director won EVE", body: "You typed 'can I have your stuff?' before anyone said goodbye. The departing director sends you 100M. Collect it.", source: "research.html#card-quitting", effect: { type: "cash", value: 100 } }
  ],
  localCards: [
    { title: "Premium renter experience", body: "The landlord calls this the penthouse. The jump freighter pilot disagrees. Advance to Tenal. Collect 200M if you pass Undock.", source: "research.html#card-renters", effect: { type: "move", index: 39 } },
    { title: "Stain gate road trip", body: "They finally built the gate. Your FC still set destination to home. Advance to Undock and collect 200M.", source: "research.html#card-stain", effect: { type: "move", index: 0 } },
    { title: "Content deployment", body: "You were promised small gangs. Two coalitions showed up. Advance to Wicked Creek. Collect 200M if you pass Undock.", source: "research.html#card-renters", effect: { type: "move", index: 24 } },
    { title: "Floodplain doctrine", body: "The landlord called it a fortress until the evac ping. Advance to Pure Blind. Collect 200M if you pass Undock.", source: "research.html#card-coping", effect: { type: "move", index: 11 } },
    { title: "Ansiblex toll doubled", body: "You paid to build it. Now pay to use it. Advance to the nearest jump bridge. If unowned, buy or auction it; if owned by a rival, pay twice normal rent. Collect 200M if you pass Undock.", source: "research.html#card-bridges", effect: { type: "nearestTransit" } },
    { title: "Blue standings, red invoice", body: "Your diplomat negotiated access and forgot to ask the price. Advance to the nearest jump bridge. If unowned, buy or auction it; if owned by a rival, pay twice normal rent. Collect 200M if you pass Undock.", source: "research.html#card-bridges", effect: { type: "nearestTransit" } },
    { title: "ESS keys in the wrong hangar", body: "The key is in Jita. The defense fleet is here. Advance to the nearest utility. If owned by a rival, roll fresh dice and pay ten times the total. If unowned, buy or auction it. Collect 200M if you pass Undock.", source: "research.html#card-ess", effect: { type: "nearestUtility" } },
    { title: "FW LP cashout", body: "You sold before the spreadsheet got posted. Collect 50M.", source: "research.html#card-fw", effect: { type: "cash", value: 50 } },
    { title: "Streamer's week off", kicker: "BACK BEFORE THE THREAD IS LOCKED", body: "The Loru megathread has outlasted your timeout. So much for winning EVE. Get out of Winning EVE free. Keep this card until needed, or trade it.", source: "research.html#streamer", effect: { type: "escape" } },
    { title: "M2 ghost ship", body: "You loaded grid. Your titan stayed home and died anyway. Move back three spaces.", source: "research.html#card-m2", effect: { type: "back", value: 3 } },
    { title: "Banned for RMT", body: "Your wallet was more interesting than your killboard. CCP helped you win EVE. Go directly to Winning EVE and touch grass. Do not pass Undock. Do not collect 200M.", source: "research.html#card-security", effect: { type: "jail" } },
    { title: "Red dot in the fuel bay", body: "You cleared the notification. Nobody bought fuel. Pay 25M per Astrahus and 100M per Keepstar you own for repairs.", source: "research.html#card-red-dot", effect: { type: "classicRepairs", house: 25, hotel: 100 } },
    { title: "Jumped on contact", body: "FC said 'don't jump.' You heard the important bit. Pay 15M for the replacement tackle.", source: "research.html#card-fleet", effect: { type: "cash", value: -15 } },
    { title: "Can I bring my Drake?", body: "FC has stopped answering. Advance to Hek → Turnur. Collect 200M if you pass Undock.", source: "research.html#card-fleet", effect: { type: "move", index: 5 } },
    { title: "Blue donut diplomacy", body: "You blued the last neutral in the region. Every ally wants a signing bonus. Pay every other pilot 50M.", source: "research.html#card-renters", effect: { type: "payAll", value: 50 } },
    { title: "The rent cleared", body: "The tenants docked their Ishtars for a lone Heron, then paid you for 'premium protection.' Collect 150M.", source: "research.html#card-renters", effect: { type: "cash", value: 150 } }
  ],
  botProfiles: [
    { name: "RAT_BOT-03", ship: "assets/drake.png", color: "#ecb54a", motto: "aligned and calculating", strategyLabel: "Yield Hunter", strategy: { reserve: 240, baseBuy: 0.65, buyThreshold: 0.59, upgradeReserve: 360, upgradeBias: 0.92, denial: 0.3, variance: 0.05, preferredGroups: ["orange", "red", "yellow"], preferredTypes: ["utility"] } },
    { name: "RENT_DUE", ship: "assets/dominix.png", color: "#df6f73", motto: "your loss is modeled", strategyLabel: "Set Breaker", strategy: { reserve: 180, baseBuy: 0.7, buyThreshold: 0.57, upgradeReserve: 320, upgradeBias: 0.98, denial: 0.42, variance: 0.04, preferredGroups: ["orange", "green", "blue"] } },
    { name: "HAUL_BOT", ship: "assets/providence.png", color: "#8b82e8", motto: "liquidity is cargo", strategyLabel: "Network Baron", strategy: { reserve: 300, baseBuy: 0.63, buyThreshold: 0.6, upgradeReserve: 400, upgradeBias: 0.88, denial: 0.34, variance: 0.06, preferredTypes: ["transit", "utility"], preferredGroups: ["cyan", "magenta", "orange"] } }
  ]
};

if (typeof module !== "undefined" && module.exports) module.exports = GAME_DATA;
