// Hotspots: public ESI roster + Sep 2025–Aug 2026 zKillboard history. See research.html.
const GAME_DATA = {
  salary: 200,
  startingCash: 1500,
  maxUpgrades: 5,
  factions: {"calmil":{"name":"CALMIL","militia":"State Protectorate","color":"#73c5ff"},"galmil":{"name":"GALMIL","militia":"Federal Defense Union","color":"#77dda4"}},
  groups: {"brown":{"name":"Outer Patrol","color":"#9b6b4a"},"cyan":{"name":"Roaming Circuit","color":"#53cbd8"},"magenta":{"name":"Skirmish Line","color":"#c45ab3"},"orange":{"name":"Supply Pressure","color":"#e99b42"},"red":{"name":"Forward Staging","color":"#e05255"},"yellow":{"name":"Fleet Form-up","color":"#e6c54f"},"green":{"name":"Warzone Crucible","color":"#4eb07c"},"blue":{"name":"Perpetual Content","color":"#437ed8"}},
  spaces: [
    {"type":"corner","name":"Undock","icon":"◆","text":"Militia resupply pays 200M each circuit. Try to bring the ship back."},
    {"type":"property","name":"Fliet","group":"brown","price":60,"buildCost":50,"rent":[2,10,30,90,160,250],"flavor":"The replacement frigates have their own replacement frigates.","systemId":30004980,"region":"Essence","source":"research.html#hotspots"},
    {"type":"card","deck":"mail","name":"Militia Orders","icon":"✉","text":"Read the ping. The second one. The one after that."},
    {"type":"property","name":"Mercomesier","group":"brown","price":60,"buildCost":50,"rent":[4,20,60,180,320,450],"flavor":"The scout pronounced it three different ways. All three are camped.","systemId":30003853,"region":"Placid","source":"research.html#hotspots"},
    {"type":"tax","name":"LP Store Fees","amount":200,"icon":"▤","text":"The LP was free. The tags, ISK, and replacement ships were not."},
    {"type":"transit","name":"State Shipcaster","price":200,"icon":"⇄","text":"Onnamon departure. A fast route to someone else’s optimal range."},
    {"type":"property","name":"Moclinamaud","group":"cyan","price":100,"buildCost":50,"rent":[6,30,90,270,400,550],"flavor":"Fleet spent longer spelling the destination than taking the fight.","systemId":30003828,"region":"Placid","source":"research.html#hotspots"},
    {"type":"card","deck":"local","name":"Local Comms","icon":"⌁","text":"The fight is over. The argument has just undocked."},
    {"type":"property","name":"Tannolen","group":"cyan","price":100,"buildCost":50,"rent":[6,30,90,270,400,550],"flavor":"Just one more plex. The oldest lie in the warzone.","systemId":30002812,"region":"The Citadel","source":"research.html#hotspots"},
    {"type":"property","name":"Evaulon","group":"cyan","price":120,"buildCost":50,"rent":[8,40,100,300,450,600],"flavor":"Your drones stayed to defend the Federation. Please come back for them.","systemId":30003839,"region":"Placid","source":"research.html#hotspots"},
    {"type":"corner","name":"Reship Bay","caption":"JUST RESHIPPING","icon":"⚠","text":"Your pod made it home. Your dignity is still on grid. Jail rules apply; normal landings are just visiting."},
    {"type":"property","name":"Old Man Star","group":"magenta","price":140,"buildCost":100,"rent":[10,50,150,450,625,750],"flavor":"The old man has seen this fit die before.","systemId":30005000,"region":"Essence","source":"research.html#hotspots"},
    {"type":"utility","name":"Militia LP Store","price":150,"icon":"⌬","text":"Your wallet is imaginary until somebody buys the faction ammunition."},
    {"type":"property","name":"Onatoh","group":"magenta","price":140,"buildCost":100,"rent":[10,50,150,450,625,750],"flavor":"A short roam, measured in replacement hulls.","systemId":30002811,"region":"The Citadel","source":"research.html#hotspots"},
    {"type":"property","name":"Athounon","group":"magenta","price":160,"buildCost":100,"rent":[12,60,180,500,700,900],"flavor":"The destination is settled. The militia argument is not.","systemId":30003856,"region":"Placid","source":"research.html#hotspots"},
    {"type":"transit","name":"Federal Shipcaster","price":200,"icon":"⇄","text":"Intaki departure. Freedom of movement, subject to the landing grid."},
    {"type":"property","name":"Aubenall","group":"orange","price":180,"buildCost":100,"rent":[14,70,200,550,750,950],"flavor":"The reship market has excellent repeat customers.","systemId":30003827,"region":"Placid","source":"research.html#hotspots"},
    {"type":"card","deck":"mail","name":"Militia Orders","icon":"✉","text":"Read the ping. The second one. The one after that."},
    {"type":"property","name":"Hikkoken","group":"orange","price":180,"buildCost":100,"rent":[14,70,200,550,750,950],"flavor":"Your safe spot is only safe until the probes agree.","systemId":30045338,"region":"Black Rise","source":"research.html#hotspots"},
    {"type":"property","name":"Oinasiken","group":"orange","price":200,"buildCost":100,"rent":[16,80,220,600,800,1000],"flavor":"Both militias called it a strategic withdrawal. The wrecks stayed.","systemId":30045347,"region":"Black Rise","source":"research.html#hotspots"},
    {"type":"corner","name":"Ship Spinning","icon":"◇","text":"Safe inside. Winning in Local. Free Parking pays nothing."},
    {"type":"property","name":"Kinakka","group":"red","price":220,"buildCost":150,"rent":[18,90,250,700,875,1050],"flavor":"You came looking for a fair fight. Local appreciates the joke.","systemId":30045314,"region":"Black Rise","source":"research.html#hotspots"},
    {"type":"card","deck":"local","name":"Local Comms","icon":"⌁","text":"The fight is over. The argument has just undocked."},
    {"type":"property","name":"Deven","group":"red","price":220,"buildCost":150,"rent":[18,90,250,700,875,1050],"flavor":"The fleet is one jump out. It has been one jump out for twenty minutes.","systemId":30004985,"region":"Essence","source":"research.html#hotspots"},
    {"type":"property","name":"Renarelle","group":"red","price":240,"buildCost":150,"rent":[20,100,300,750,925,1100],"flavor":"The button needs defending. Everyone has volunteered to chase the frigate.","systemId":30003829,"region":"Placid","source":"research.html#hotspots"},
    {"type":"transit","name":"Supply Convoy","price":200,"icon":"⇄","text":"A hundred fitted frigates. Somehow, nobody packed ammo."},
    {"type":"property","name":"Nennamaila","group":"yellow","price":260,"buildCost":150,"rent":[22,110,330,800,975,1150],"flavor":"Your FC said bring a spare. You thought they meant ammunition.","systemId":30045344,"region":"Black Rise","source":"research.html#hotspots"},
    {"type":"property","name":"Abune","group":"yellow","price":260,"buildCost":150,"rent":[22,110,330,800,975,1150],"flavor":"The Comet has a police light. It does not have a warrant.","systemId":30004984,"region":"Essence","source":"research.html#hotspots"},
    {"type":"utility","name":"Propaganda Relay","price":150,"icon":"◈","text":"Both sides won the fight. Both broadcasts need funding."},
    {"type":"property","name":"Nagamanen","group":"yellow","price":280,"buildCost":150,"rent":[24,120,360,850,1025,1200],"flavor":"The overview is red. The killboard editor calls that a target-rich environment.","systemId":30002807,"region":"The Citadel","source":"research.html#hotspots"},
    {"type":"gotojail","name":"Gate Camp","icon":"»","text":"The scout said clear. Go directly to Reship Bay. Do not pass Undock. Do not collect 200M."},
    {"type":"property","name":"Heydieles","group":"green","price":300,"buildCost":200,"rent":[26,130,390,900,1100,1275],"flavor":"Squids and frogs agree on one thing: the other side brought too many.","systemId":30004979,"region":"Essence","source":"research.html#hotspots"},
    {"type":"property","name":"Vlillirier","group":"green","price":300,"buildCost":200,"rent":[26,130,390,900,1100,1275],"flavor":"The frogs have a home-field advantage. The squids have another fleet.","systemId":30003836,"region":"Placid","source":"research.html#hotspots"},
    {"type":"card","deck":"mail","name":"Militia Orders","icon":"✉","text":"Read the ping. The second one. The one after that."},
    {"type":"property","name":"Sujarento","group":"green","price":320,"buildCost":200,"rent":[28,150,450,1000,1200,1400],"flavor":"The scout said clear. Technically, the wrecks do not tackle.","systemId":30002809,"region":"The Citadel","source":"research.html#hotspots"},
    {"type":"transit","name":"Reship Express","price":200,"icon":"⇄","text":"Same pilot. Same fit. Optimism has no cooldown."},
    {"type":"card","deck":"local","name":"Local Comms","icon":"⌁","text":"The fight is over. The argument has just undocked."},
    {"type":"property","name":"Aldranette","group":"blue","price":350,"buildCost":200,"rent":[35,175,500,1100,1300,1500],"flavor":"The front moved. Your entire hangar would like a word.","systemId":30003837,"region":"Placid","source":"research.html#hotspots"},
    {"type":"tax","name":"War Chest","amount":100,"icon":"₭","text":"A voluntary contribution, already deducted."},
    {"type":"property","name":"Tama","group":"blue","price":400,"buildCost":200,"rent":[50,200,600,1400,1700,2000],"flavor":"Welcome to lowsec. Your complimentary pod express is boarding.","systemId":30002813,"region":"The Citadel","source":"research.html#hotspots"}
  ],
  mailCards: [
    {"title":"FC moved staging","body":"You finished moving the hangar. FC posted a new destination. Advance to Undock and collect 200M.","source":"research.html#card-logistics","effect":{"type":"move","index":0}},
    {"title":"LP cash-out window","body":"You sold the faction ammo before militia chat discovered the same spreadsheet. Collect 200M.","source":"research.html#card-lp","effect":{"type":"cash","value":200}},
    {"title":"Wrong hull, right enthusiasm","body":"You brought an assault frigate to a Navy plex. The gate is not impressed by your skill points. Pay 50M to reship.","source":"research.html#card-plex","effect":{"type":"cash","value":-50}},
    {"title":"Calamari buyback","body":"The loot officer bought the squid wrecks. Apparently patriotism has a sell order. Collect 50M.","source":"research.html#card-militias","effect":{"type":"cash","value":50}},
    {"title":"Instawarp bookmark","body":"A corpmate finally shared the undock bookmark. Get out of Reship Bay free. Keep this card until needed, or trade it.","source":"research.html#card-reship","effect":{"type":"escape"}},
    {"title":"Undock is red","body":"You tested the undock with the expensive fit. Go directly to Reship Bay. Do not pass Undock or collect 200M.","source":"research.html#card-reship","effect":{"type":"jail"}},
    {"title":"SRP approved","body":"Correct hull. Correct fit. Wrong outcome. The militia reimburses you anyway. Collect 100M.","source":"research.html#card-fleet","effect":{"type":"cash","value":100}},
    {"title":"Ammo buyback","body":"The quartermaster found your spare charges. All seventeen stacks of them. Collect 20M.","source":"research.html#card-logistics","effect":{"type":"cash","value":20}},
    {"title":"Birthday reship fleet","body":"Everyone brought a tackle frigate. Nobody brought an exit plan. Collect 10M from every other pilot for your birthday hull.","source":"research.html#card-fleet","effect":{"type":"collectAll","value":10}},
    {"title":"Insurance is doctrine","body":"The ship lasted less time than the insurance quote. At least one part of the plan worked. Collect 100M.","source":"research.html#card-reship","effect":{"type":"cash","value":100}},
    {"title":"Purple is not a tank","body":"Your overview said friendly. The lossmail has a different opinion. Pay 100M for replacement ships.","source":"research.html#card-awox","effect":{"type":"cash","value":-100}},
    {"title":"Forgot the tags","body":"You have the LP. You have the ISK. The store would also like the items you left five jumps back. Pay 50M.","source":"research.html#card-lp","effect":{"type":"cash","value":-50}},
    {"title":"Drone recovery service","body":"The Gallente fleet left. Its drones are still contributing to the war effort, now in your cargo. Collect 25M.","source":"research.html#card-militias","effect":{"type":"cash","value":25}},
    {"title":"Fuel is a doctrine","body":"Everyone funded another fleet. Nobody funded the citadels. Pay 40M per Astrahus and 115M per Keepstar you own for repairs.","source":"research.html#card-structures","effect":{"type":"classicRepairs","house":40,"hotel":115}},
    {"title":"Propaganda runner-up","body":"Your victory poster came second. The other side used the same battle report. Collect 10M.","source":"research.html#card-propaganda","effect":{"type":"cash","value":10}},
    {"title":"Newbro care package","body":"A veteran asked what you needed. You said one frigate. The contract contains twenty. Collect 100M.","source":"research.html#card-fleet","effect":{"type":"cash","value":100}}
  ],
  localCards: [
    {"title":"Content on the gate","body":"Your scout found a fight. Your scout is now part of the scenery. Advance to Tama. Collect 200M if you pass Undock.","source":"research.html#card-hotspots","effect":{"type":"move","index":39}},
    {"title":"Forgot ammo again","body":"The fit was perfect in the simulator. Advance to Undock and collect 200M. Try the cargo hold this time.","source":"research.html#card-logistics","effect":{"type":"move","index":0}},
    {"title":"The battlefield ping","body":"You asked for small gang. The entire militia clicked Interested. Advance to Renarelle. Collect 200M if you pass Undock.","source":"research.html#card-plex","effect":{"type":"move","index":24}},
    {"title":"Button needs orbiting","body":"Command calls it a vital military objective. Your ship calls it a circle. Advance to Old Man Star. Collect 200M if you pass Undock.","source":"research.html#card-plex","effect":{"type":"move","index":11}},
    {"title":"Shipcaster express","body":"You saved twelve jumps and arrived directly in somebody’s story. Advance to the nearest logistics route. If unowned, buy or auction it; if owned by a rival, pay twice normal rent. Collect 200M if you pass Undock.","source":"research.html#card-logistics","effect":{"type":"nearestTransit"}},
    {"title":"FC said take the gate","body":"FC meant the other gate. Advance to the nearest logistics route. If unowned, buy or auction it; if owned by a rival, pay twice normal rent. Collect 200M if you pass Undock.","source":"research.html#card-logistics","effect":{"type":"nearestTransit"}},
    {"title":"Loyalty has overheads","body":"The militia has excellent benefits. Please see the attached invoice. Advance to the nearest utility. If owned by a rival, roll fresh dice and pay ten times the total. If unowned, buy or auction it. Collect 200M if you pass Undock.","source":"research.html#card-lp","effect":{"type":"nearestUtility"}},
    {"title":"Patriotic market timing","body":"You believe in your faction. You believe in selling before everybody else a little more. Collect 50M.","source":"research.html#card-lp","effect":{"type":"cash","value":50}},
    {"title":"Spare hull on contract","body":"The quartermaster prepared for exactly this level of competence. Get out of Reship Bay free. Keep this card until needed, or trade it.","source":"research.html#card-reship","effect":{"type":"escape"}},
    {"title":"The plex despawned","body":"You bookmarked the site. The site did not book you. Move back three spaces.","source":"research.html#card-plex","effect":{"type":"back","value":3}},
    {"title":"One more jump","body":"The fleet voted to keep roaming. The gate camp voted unanimously. Go directly to Reship Bay. Do not pass Undock. Do not collect 200M.","source":"research.html#card-reship","effect":{"type":"jail"}},
    {"title":"Docking fees, with explosions","body":"Your forward base has become the enemy’s evening plan. Pay 25M per Astrahus and 100M per Keepstar you own for repairs.","source":"research.html#card-structures","effect":{"type":"classicRepairs","house":25,"hotel":100}},
    {"title":"Heat management","body":"You overheated the afterburner through the post-fight argument. Pay 15M for repairs.","source":"research.html#card-fleet","effect":{"type":"cash","value":-15}},
    {"title":"Squid delivery service","body":"The State supplied the transport. Survival is a separate department. Advance to State Shipcaster. Collect 200M if you pass Undock.","source":"research.html#card-logistics","effect":{"type":"move","index":5}},
    {"title":"Seagull convention","body":"You did the fighting. Everyone else arrived for the payout. Pay every other pilot 50M.","source":"research.html#card-awox","effect":{"type":"payAll","value":50}},
    {"title":"We won the ISK war","body":"The objective is gone, but the loot sold. Your after-action report leads with the good news. Collect 150M.","source":"research.html#card-propaganda","effect":{"type":"cash","value":150}}
  ],
  botProfiles: [
    {"name":"SQUID_FC","ship":"assets/drake.png","color":"#78a5e8","motto":"the spreadsheet demands a fleet","strategyLabel":"LP Broker","strategy":{"reserve":240,"baseBuy":0.65,"buyThreshold":0.59,"upgradeReserve":360,"upgradeBias":0.92,"denial":0.3,"variance":0.05,"preferredGroups":["orange","red","yellow"],"preferredTypes":["utility"]},"shipName":"Drake","faction":"calmil"},
    {"name":"FROG_FC","ship":"assets/dominix.png","color":"#83d6a2","motto":"liberation, with blasters","strategyLabel":"System Breaker","strategy":{"reserve":180,"baseBuy":0.7,"buyThreshold":0.57,"upgradeReserve":320,"upgradeBias":0.98,"denial":0.42,"variance":0.04,"preferredGroups":["orange","green","blue"]},"shipName":"Dominix","faction":"galmil"},
    {"name":"PLEX_MARSHAL","ship":"assets/catalyst.png","color":"#e2c76e","motto":"one more button","strategyLabel":"Supply Marshal","strategy":{"reserve":300,"baseBuy":0.63,"buyThreshold":0.6,"upgradeReserve":400,"upgradeBias":0.88,"denial":0.34,"variance":0.06,"preferredTypes":["transit","utility"],"preferredGroups":["cyan","magenta","orange"]},"shipName":"Catalyst","faction":"galmil"}
  ]
};

if (typeof module !== "undefined" && module.exports) module.exports = GAME_DATA;
